//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiHang
    {
        public LoaiHang()
        {
            this.HangHoas = new HashSet<HangHoa>();
        }
    
        public int MaLH { get; set; }
        public string TenLH { get; set; }
    
        public virtual ICollection<HangHoa> HangHoas { get; set; }
    }
}
